#!/usr/bin/env bash
#
# setup_tunnel.sh — One-time setup for a named Cloudflare Tunnel.
#
# Creates a persistent tunnel so you get the same URL across restarts.
# Requires a free Cloudflare account (opens browser to authenticate).
#
# Usage: bash scripts/setup_tunnel.sh [tunnel-name]
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TUNNEL_NAME="${1:-voice-assistant}"
CONFIG_FILE="$REPO_ROOT/.tunnel-config"

echo "=== Named Cloudflare Tunnel Setup ==="
echo ""

# ── Check cloudflared ──────────────────────────────────────────
if ! command -v cloudflared >/dev/null 2>&1; then
  echo "ERROR: cloudflared not found"
  echo "  Install: brew install cloudflared"
  exit 1
fi
echo "  cloudflared: $(cloudflared --version 2>&1 | head -1)"

# ── Check for existing config ─────────────────────────────────
if [ -f "$CONFIG_FILE" ]; then
  echo ""
  echo "  Existing tunnel config found: $CONFIG_FILE"
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
  echo "  Tunnel name: ${TUNNEL_NAME:-unknown}"
  echo "  Tunnel ID:   ${TUNNEL_ID:-unknown}"
  echo ""
  read -rp "  Overwrite? [y/N]: " OVERWRITE
  if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
    echo "  Keeping existing config."
    exit 0
  fi
  echo ""
fi

# ── Step 1: Authenticate ──────────────────────────────────────
echo "Step 1: Authenticate with Cloudflare"
echo "  This opens your browser to log in (free account works)."
echo ""
read -rp "  Press Enter to open browser..." _

cloudflared tunnel login

echo ""
echo "  Authenticated."

# ── Step 2: Create tunnel ─────────────────────────────────────
echo ""
echo "Step 2: Creating tunnel '$TUNNEL_NAME'..."

# Check if tunnel already exists
if cloudflared tunnel info "$TUNNEL_NAME" >/dev/null 2>&1; then
  echo "  Tunnel '$TUNNEL_NAME' already exists."
  TUNNEL_ID=$(cloudflared tunnel info "$TUNNEL_NAME" 2>&1 | grep -oE '[a-f0-9-]{36}' | head -1)
else
  CREATE_OUTPUT=$(cloudflared tunnel create "$TUNNEL_NAME" 2>&1)
  echo "$CREATE_OUTPUT"
  TUNNEL_ID=$(echo "$CREATE_OUTPUT" | grep -oE '[a-f0-9-]{36}' | head -1)
fi

if [ -z "$TUNNEL_ID" ]; then
  echo "ERROR: Could not determine tunnel ID."
  echo "  Try: cloudflared tunnel list"
  exit 1
fi

echo "  Tunnel ID: $TUNNEL_ID"

# ── Step 3: Optional DNS routing ──────────────────────────────
TUNNEL_DOMAIN=""
echo ""
echo "Step 3: DNS routing (optional)"
echo ""
echo "  Without a domain, your URL will be:"
echo "    https://${TUNNEL_ID}.cfargotunnel.com"
echo ""
echo "  If you have a domain on Cloudflare, you can map a subdomain."
echo "  Example: voice.yourdomain.com"
echo ""
read -rp "  Custom subdomain (or press Enter to skip): " TUNNEL_DOMAIN

if [ -n "$TUNNEL_DOMAIN" ]; then
  # If user entered just a subdomain (no dots), get the zone from the cert
  if [[ "$TUNNEL_DOMAIN" != *.* ]]; then
    # Extract zone from the origin cert
    ZONE=$(openssl x509 -in ~/.cloudflared/cert.pem -noout -subject 2>/dev/null | grep -oE '[a-zA-Z0-9-]+\.[a-zA-Z]{2,}$' || echo "")
    if [ -n "$ZONE" ]; then
      TUNNEL_DOMAIN="${TUNNEL_DOMAIN}.${ZONE}"
    else
      echo "  Could not detect zone from cert. Please enter the full subdomain"
      echo "  (e.g. voice.yourdomain.com):"
      read -rp "  Full subdomain: " TUNNEL_DOMAIN
    fi
  fi
  echo "  Routing $TUNNEL_DOMAIN → tunnel '$TUNNEL_NAME'..."
  cloudflared tunnel route dns "$TUNNEL_NAME" "$TUNNEL_DOMAIN"
  TUNNEL_URL="https://$TUNNEL_DOMAIN"
  echo "  DNS route created."
else
  TUNNEL_URL="https://${TUNNEL_ID}.cfargotunnel.com"
fi

# ── Save config ───────────────────────────────────────────────
cat > "$CONFIG_FILE" <<EOF
# Named Cloudflare Tunnel config (auto-generated by setup_tunnel.sh)
# Do not commit — contains environment-specific tunnel identity.
TUNNEL_NAME=$TUNNEL_NAME
TUNNEL_ID=$TUNNEL_ID
TUNNEL_URL=$TUNNEL_URL
EOF

echo ""
echo "  Config saved to: $CONFIG_FILE"

# ── Summary ───────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Tunnel:  $TUNNEL_NAME"
echo "  ID:      $TUNNEL_ID"
echo "  URL:     $TUNNEL_URL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  This URL is permanent. Share it once, use it forever."
echo ""
echo "  Next: run 'bash scripts/run.sh' and select mode 3 (Cellular)."
echo "  The named tunnel will be used automatically."
echo ""
